### ISSUE TITLE
Quarto ext font awesome error 

### ISSUE THREAD

**Issue by bradfordjohnson** [bradfordjohnson/quarto-portfolio#33]
Error when trying to render on mac
- RStudio is updated
- All Packages updated
- Quarto updated

Quarto version: `1.1.189`

<img width="1153" alt="Screenshot 2023-03-13 at 1 39 42 PM" src="https://user-images.githubusercontent.com/111791965/224783598-22a0f8ef-5346-49ca-b09e-833b6cc00916.png">

**Comment by bradfordjohnson** [comment]
Extension YAML
```YAML
title: Font Awesome support
author: Carlos Scheidegger
version: 1.1.0
quarto-required: ">=1.2.269"
contributes:
  shortcodes:
    - fontawesome.lua
```

Might not be able to render this quarto project with extension dependency until quarto releases update for Mac OS
